name: RATE Build test
on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - release/*
      - feat/*
      - master

jobs:
  rate-build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Install Latest Docker Compose
        run: |
            COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep 'tag_name' | cut -d\" -f4)
            DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
            mkdir -p $DOCKER_CONFIG/cli-plugins
            sudo curl -SL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o $DOCKER_CONFIG/cli-plugins/docker-compose
            sudo chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose

      - name: Check Docker Compose Version
        run: docker compose version

      - name: Build RATE with docker compose
        run: docker compose build rate